# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\keato\git\acoustics_101\pa_methods.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PaMethodsWindow(object):
    def setupUi(self, PaMethodsWindow):
        PaMethodsWindow.setObjectName("PaMethodsWindow")
        PaMethodsWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(PaMethodsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.methodsAndProceduresTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.methodsAndProceduresTabs.setObjectName("methodsAndProceduresTabs")
        self.methodOfAdjustmentTab = QtWidgets.QWidget()
        self.methodOfAdjustmentTab.setObjectName("methodOfAdjustmentTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.methodOfAdjustmentTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsLayout = QtWidgets.QVBoxLayout()
        self.settingsLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.settingsLayout.setContentsMargins(10, 10, 10, 10)
        self.settingsLayout.setSpacing(10)
        self.settingsLayout.setObjectName("settingsLayout")
        self.testSelectorLayout = QtWidgets.QVBoxLayout()
        self.testSelectorLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.testSelectorLayout.setContentsMargins(25, 10, 25, 25)
        self.testSelectorLayout.setSpacing(10)
        self.testSelectorLayout.setObjectName("testSelectorLayout")
        self.testSelectorLabel = QtWidgets.QLabel(self.methodOfAdjustmentTab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.testSelectorLabel.setFont(font)
        self.testSelectorLabel.setObjectName("testSelectorLabel")
        self.testSelectorLayout.addWidget(self.testSelectorLabel, 0, QtCore.Qt.AlignHCenter)
        self.testSelectorDropdown = QtWidgets.QComboBox(self.methodOfAdjustmentTab)
        self.testSelectorDropdown.setMinimumSize(QtCore.QSize(200, 0))
        self.testSelectorDropdown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.testSelectorDropdown.setObjectName("testSelectorDropdown")
        self.testSelectorDropdown.addItem("")
        self.testSelectorDropdown.addItem("")
        self.testSelectorDropdown.addItem("")
        self.testSelectorLayout.addWidget(self.testSelectorDropdown, 0, QtCore.Qt.AlignHCenter)
        self.settingsLayout.addLayout(self.testSelectorLayout)
        self.testControlLayout = QtWidgets.QVBoxLayout()
        self.testControlLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.testControlLayout.setContentsMargins(10, 10, 10, 10)
        self.testControlLayout.setSpacing(10)
        self.testControlLayout.setObjectName("testControlLayout")
        self.testControlLabel = QtWidgets.QLabel(self.methodOfAdjustmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testControlLabel.sizePolicy().hasHeightForWidth())
        self.testControlLabel.setSizePolicy(sizePolicy)
        self.testControlLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.testControlLabel.setFont(font)
        self.testControlLabel.setObjectName("testControlLabel")
        self.testControlLayout.addWidget(self.testControlLabel, 0, QtCore.Qt.AlignHCenter)
        self.testControlButtonLayout = QtWidgets.QHBoxLayout()
        self.testControlButtonLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.testControlButtonLayout.setContentsMargins(10, 10, 10, 10)
        self.testControlButtonLayout.setSpacing(10)
        self.testControlButtonLayout.setObjectName("testControlButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.testControlButtonLayout.addItem(spacerItem)
        self.testControlStartButton = QtWidgets.QPushButton(self.methodOfAdjustmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testControlStartButton.sizePolicy().hasHeightForWidth())
        self.testControlStartButton.setSizePolicy(sizePolicy)
        self.testControlStartButton.setMinimumSize(QtCore.QSize(100, 0))
        self.testControlStartButton.setMaximumSize(QtCore.QSize(100, 200))
        self.testControlStartButton.setObjectName("testControlStartButton")
        self.testControlButtonLayout.addWidget(self.testControlStartButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.testControlButtonLayout.addItem(spacerItem1)
        self.testControlStopButton = QtWidgets.QPushButton(self.methodOfAdjustmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testControlStopButton.sizePolicy().hasHeightForWidth())
        self.testControlStopButton.setSizePolicy(sizePolicy)
        self.testControlStopButton.setMinimumSize(QtCore.QSize(100, 0))
        self.testControlStopButton.setMaximumSize(QtCore.QSize(100, 200))
        self.testControlStopButton.setObjectName("testControlStopButton")
        self.testControlButtonLayout.addWidget(self.testControlStopButton)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.testControlButtonLayout.addItem(spacerItem2)
        self.testControlLayout.addLayout(self.testControlButtonLayout)
        self.settingsLayout.addLayout(self.testControlLayout)
        self.testInstructionsLayout = QtWidgets.QVBoxLayout()
        self.testInstructionsLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.testInstructionsLayout.setContentsMargins(25, 10, 25, 10)
        self.testInstructionsLayout.setSpacing(10)
        self.testInstructionsLayout.setObjectName("testInstructionsLayout")
        self.testInstructionsLabel = QtWidgets.QLabel(self.methodOfAdjustmentTab)
        self.testInstructionsLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.testInstructionsLabel.setFont(font)
        self.testInstructionsLabel.setObjectName("testInstructionsLabel")
        self.testInstructionsLayout.addWidget(self.testInstructionsLabel, 0, QtCore.Qt.AlignHCenter)
        self.testInstructionsDialog = QtWidgets.QTextEdit(self.methodOfAdjustmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testInstructionsDialog.sizePolicy().hasHeightForWidth())
        self.testInstructionsDialog.setSizePolicy(sizePolicy)
        self.testInstructionsDialog.setMinimumSize(QtCore.QSize(325, 200))
        self.testInstructionsDialog.setMaximumSize(QtCore.QSize(500, 16777215))
        self.testInstructionsDialog.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.testInstructionsDialog.setStyleSheet("")
        self.testInstructionsDialog.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.testInstructionsDialog.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.testInstructionsDialog.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.testInstructionsDialog.setReadOnly(True)
        self.testInstructionsDialog.setObjectName("testInstructionsDialog")
        self.testInstructionsLayout.addWidget(self.testInstructionsDialog, 0, QtCore.Qt.AlignHCenter)
        self.settingsLayout.addLayout(self.testInstructionsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.settingsLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.settingsLayout)
        self.plotAndStimulusControlLayout = QtWidgets.QVBoxLayout()
        self.plotAndStimulusControlLayout.setContentsMargins(25, 10, 25, 10)
        self.plotAndStimulusControlLayout.setSpacing(10)
        self.plotAndStimulusControlLayout.setObjectName("plotAndStimulusControlLayout")
        self.testResultsPlot = PlotWidget(self.methodOfAdjustmentTab)
        self.testResultsPlot.setObjectName("testResultsPlot")
        self.plotAndStimulusControlLayout.addWidget(self.testResultsPlot)
        self.stimulusControlLayout = QtWidgets.QVBoxLayout()
        self.stimulusControlLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.stimulusControlLayout.setContentsMargins(20, 10, 20, 10)
        self.stimulusControlLayout.setSpacing(10)
        self.stimulusControlLayout.setObjectName("stimulusControlLayout")
        self.stimulusControlLabel = QtWidgets.QLabel(self.methodOfAdjustmentTab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stimulusControlLabel.setFont(font)
        self.stimulusControlLabel.setObjectName("stimulusControlLabel")
        self.stimulusControlLayout.addWidget(self.stimulusControlLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stimulusControlSlider = FloatSlider(self.methodOfAdjustmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stimulusControlSlider.sizePolicy().hasHeightForWidth())
        self.stimulusControlSlider.setSizePolicy(sizePolicy)
        self.stimulusControlSlider.setMinimum(100)
        self.stimulusControlSlider.setMaximum(5000)
        self.stimulusControlSlider.setProperty("value", 1000)
        self.stimulusControlSlider.setOrientation(QtCore.Qt.Horizontal)
        self.stimulusControlSlider.setObjectName("stimulusControlSlider")
        self.stimulusControlLayout.addWidget(self.stimulusControlSlider)
        self.stimulusButton = QtWidgets.QPushButton(self.methodOfAdjustmentTab)
        self.stimulusButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stimulusButton.setObjectName("stimulusButton")
        self.stimulusControlLayout.addWidget(self.stimulusButton, 0, QtCore.Qt.AlignHCenter)
        self.plotAndStimulusControlLayout.addLayout(self.stimulusControlLayout)
        self.horizontalLayout.addLayout(self.plotAndStimulusControlLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.MethodOfAdjusment = MethodOfAdjustmentWidget(self.methodOfAdjustmentTab)
        self.MethodOfAdjusment.setObjectName("MethodOfAdjusment")
        self.gridLayout_2.addWidget(self.MethodOfAdjusment, 0, 0, 1, 1)
        self.methodsAndProceduresTabs.addTab(self.methodOfAdjustmentTab, "")
        self.methodOfTrackingTab = QtWidgets.QWidget()
        self.methodOfTrackingTab.setObjectName("methodOfTrackingTab")
        self.methodsAndProceduresTabs.addTab(self.methodOfTrackingTab, "")
        self.magnitudeEstimationTab = QtWidgets.QWidget()
        self.magnitudeEstimationTab.setObjectName("magnitudeEstimationTab")
        self.methodsAndProceduresTabs.addTab(self.magnitudeEstimationTab, "")
        self.yesNoProcedureTab = QtWidgets.QWidget()
        self.yesNoProcedureTab.setObjectName("yesNoProcedureTab")
        self.methodsAndProceduresTabs.addTab(self.yesNoProcedureTab, "")
        self.twoIntervalForcedChoiceTab = QtWidgets.QWidget()
        self.twoIntervalForcedChoiceTab.setObjectName("twoIntervalForcedChoiceTab")
        self.methodsAndProceduresTabs.addTab(self.twoIntervalForcedChoiceTab, "")
        self.adaptiveProceduresTab = QtWidgets.QWidget()
        self.adaptiveProceduresTab.setObjectName("adaptiveProceduresTab")
        self.methodsAndProceduresTabs.addTab(self.adaptiveProceduresTab, "")
        self.comparisonOfStimulusPairsTab = QtWidgets.QWidget()
        self.comparisonOfStimulusPairsTab.setObjectName("comparisonOfStimulusPairsTab")
        self.methodsAndProceduresTabs.addTab(self.comparisonOfStimulusPairsTab, "")
        self.gridLayout.addWidget(self.methodsAndProceduresTabs, 0, 0, 1, 1)
        PaMethodsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PaMethodsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        PaMethodsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PaMethodsWindow)
        self.statusbar.setObjectName("statusbar")
        PaMethodsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PaMethodsWindow)
        self.methodsAndProceduresTabs.setCurrentIndex(0)
        self.testControlStartButton.clicked.connect(self.MethodOfAdjusment.start_test)
        self.testControlStopButton.clicked.connect(self.MethodOfAdjusment.stop_test)
        self.stimulusButton.clicked.connect(self.MethodOfAdjusment.update_data)
        self.stimulusControlSlider.valueChanged[float].connect(self.MethodOfAdjusment.adjust_stimulus)
        self.testSelectorDropdown.activated[str].connect(self.MethodOfAdjusment.select_test)
        QtCore.QMetaObject.connectSlotsByName(PaMethodsWindow)

    def retranslateUi(self, PaMethodsWindow):
        _translate = QtCore.QCoreApplication.translate
        PaMethodsWindow.setWindowTitle(_translate("PaMethodsWindow", "MainWindow"))
        self.testSelectorLabel.setText(_translate("PaMethodsWindow", "Select a test..."))
        self.testSelectorDropdown.setItemText(0, _translate("PaMethodsWindow", "Hearing Threshold"))
        self.testSelectorDropdown.setItemText(1, _translate("PaMethodsWindow", "Tone Match"))
        self.testSelectorDropdown.setItemText(2, _translate("PaMethodsWindow", "Octave Match"))
        self.testControlLabel.setText(_translate("PaMethodsWindow", "Test Control"))
        self.testControlStartButton.setText(_translate("PaMethodsWindow", "Start Test"))
        self.testControlStopButton.setText(_translate("PaMethodsWindow", "Stop Test"))
        self.testInstructionsLabel.setText(_translate("PaMethodsWindow", "Test Instructions"))
        self.stimulusControlLabel.setText(_translate("PaMethodsWindow", "Stimulus Control"))
        self.stimulusButton.setText(_translate("PaMethodsWindow", "Update Plot"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.methodOfAdjustmentTab), _translate("PaMethodsWindow", "Method of Adjustment"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.methodOfTrackingTab), _translate("PaMethodsWindow", "Method of Tracking"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.magnitudeEstimationTab), _translate("PaMethodsWindow", "Magnitude Estimation"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.yesNoProcedureTab), _translate("PaMethodsWindow", "Yes-No Procedure"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.twoIntervalForcedChoiceTab), _translate("PaMethodsWindow", "Two-Interval Forced Choice"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.adaptiveProceduresTab), _translate("PaMethodsWindow", "Adaptive Procedures"))
        self.methodsAndProceduresTabs.setTabText(self.methodsAndProceduresTabs.indexOf(self.comparisonOfStimulusPairsTab), _translate("PaMethodsWindow", "Comparison of Stimulus Pairs"))

from pa_methods import MethodOfAdjustmentWidget
from pyqtgraph import PlotWidget
from widgets.float_slider import FloatSlider

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaMethodsWindow = QtWidgets.QMainWindow()
    ui = Ui_PaMethodsWindow()
    ui.setupUi(PaMethodsWindow)
    PaMethodsWindow.show()
    sys.exit(app.exec_())

